### ISSUE TITLE
Can't connect to the webpage: www.hassgalaxy.app

### ISSUE THREAD

**Issue by spider7611** [Jerrkawz/HAGearS3#19]
Not safe...
What can I do?

**Comment by DavidDeSloovere** [comment]
Nothing but wait. The certificate expired a few days ago. Because the site uses HSTS, there is no way to bypass the expired certificate. We'll have to wait until the owner replaces the certificate.

@Jerrkawz I see the site runs on Heroku. You can put Cloudflare in front of the site for free and have it manage the free certificate. All you need to do I create a Cloudflare account, make sure all DNS entries are copied to Cloudflare and then change the nameservers.

**Comment by spider7611** [comment]
Can't do anything else. :)

**Comment by spider7611** [comment]
any news?

**Comment by fgccampos** [comment]
Tic tac tic tac. Waiting for the site to be available so that I can test the home assistant UI for smart watch :)

**Comment by junsve** [comment]
Change your computer time to a date before the certificate expire and it will be valid.
Don't forget to change date back again.

Edit: The cert is now updated but with wrong url (missing www). The owner needs to sort it out.

**Comment by fgccampos** [comment]
Now it allows me to connect but always returns the error:

No connection for XXXXX
Did you type the code correctly? Also make sure your watch is connected to the internet and try again.



On 15 Mar 2020 11:31, Sven Jungmar <notifications@github.com> wrote:

Change your computer time to a date before the certificate expire and it will be valid.
Don't forget to change date back again.

**Comment by Korvenwin** [comment]
> 
> 
> Change your computer time to a date before the certificate expire and it will be valid.
> Don't forget to change date back again.

The problem it is not the date.

**Comment by jerrod-lankford** [comment]
Sorry for the wait guys enabled auto certs on heroku so we shouldn't have this problem in the future
